[package]
name = "pascal_interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]

[lib]
name = "pascal_interpreter"
path = "src/lib.rs"

[[bin]]
name = "pascal_interpreter"
path = "src/main.rs"
